
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-dev:       # This job runs in the build stage, which runs first.
  stage: build
  when: on_success
  script:
    - echo "Compiling the code.."
    - echo "Compile complete."
    - echo "aaa."
  environment:
      name: dev
  only:
    - dev

deploy-dev:      # This job runs in the deploy stage.
  stage: build
  when: on_success
  only:
    - dev
  image: docker:stable
  script:
     - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
     - docker build -t $CI_REGISTRY/robiyanto/portal-pelamar-kbumn:dev -f dockerfiles/Dockerfile.dev .
     - docker push $CI_REGISTRY/robiyanto/portal-pelamar-kbumn:dev
  environment:
      name: dev

