# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-dev:       # This job runs in the build stage, which runs first.
  stage: build
  when: on_success
  only:
    - dev
  image: docker:stable  
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t registry.gitlab.com/kicky13/portal-pelamar:dev -f dockerfiles/Dockerfile.dev .
    - docker push registry.gitlab.com/kicky13/portal-pelamar:dev

deploy-dev:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script: 
    - echo "Deploying application..."
    - echo "Application successfully deployed...."