
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-QA:       # This job runs in the build stage, which runs first.
  stage: build
  when: on_success
  script:
    - echo "Compiling the code.."
    - echo "Compile complete."
    - echo "aaa."
  environment:
      name: QA
  only:
    - QA

deploy-QA:      # This job runs in the deploy stage.
  stage: deploy
  image: jenkins/ssh-agent
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSHDEV_PORTALPELAMAR" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh sisihc@10.1.150.64 -p 22 "cd /home/sisihc/frontend2"
    - echo "Application successfully deploy."
  environment:
      name: QA
  only:
    - QA

