# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-dev:       # This job runs in the build stage, which runs first.
  stage: build
  when: on_success
  only:
    - dev
  image: docker:stable  
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker build -t $CI_REGISTRY/robiyanto/portal-pelamar-kbumn:dev -f dockerfiles/Dockerfile.dev .
    # - docker push $CI_REGISTRY/robiyanto/portal-pelamar-kbumn:dev

deploy-dev:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script: 
    - echo "Deploying application..."
    - echo "Application successfully deployed...."