# build stage
FROM node:16-buster as build-stage
WORKDIR /app
COPY package*.json ./
#RUN yarn install
COPY . .
RUN yarn cache clean
RUN yarn install --network-timeout 1000000
#RUN npx browserslist@latest --update-db
RUN mv .env.dev .env
RUN yarn build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY --from=build-stage /app/conf-nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

